version: "3"

services:

  backend:

    build: ./backend

    ports:
      - "8000:8000"

    depends_on:
      - db

  frontend:

    build: ./frontend

    ports:
      - "3000:3000"

  db:

    image: postgres

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: password

      POSTGRES_DB: netsecure